### ISSUE TITLE
IREE compilation fails on some tflite models

### ISSUE THREAD

**Issue by lundong** [openxla/iree#12040]
### What happened?

For some tflite models, they can be successfully imported into mlir via iree-import-tflite. But then when we compile the mlir files via iree-compile (e.g., on llvm-cpu or vmvx backend), it returned the error messages like:

error: 'linalg.matmul' op inferred input/output operand #1 has shape's dimension #0 to be 128, but found 64

error: 'linalg.conv_2d_nhwc_hwcf' op inferred input/output operand #1 has shape's dimension #2 to be 64, but found 16

It looks like there may be some shape mismatches on some linalg ops.

Two sample failed models can be downloaded from:
https://github.com/google/lyra/blob/main/lyra/model_coeffs/soundstream_encoder.tflite
https://github.com/google/lyra/blob/main/lyra/model_coeffs/lyragan.tflite

### Steps to reproduce your issue

1. Download the models from
https://github.com/google/lyra/blob/main/lyra/model_coeffs/soundstream_encoder.tflite
https://github.com/google/lyra/blob/main/lyra/model_coeffs/lyragan.tflite
2. Build IREE
3. Import TFLite models
path/to/iree-import-tflite path/to/soundstream_encoder.tflite -o=/tmp/soundstream_encoder.mlir
path/to/iree-import-tflite path/to/lyragan.tflite -o=/tmp/lyragan.mlir
4. Use iree-compile to compile TOSA MLIRs
path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu /tmp/soundstream_encoder.mlir
path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=llvm-cpu /tmp/lyragan.mlir
5. See errors
For soundstream_encoder.mlir:
error: 'linalg.matmul' op inferred input/output operand #1 has shape's dimension #0 to be 128, but found 64...
For lyragan.mlir:
error: 'linalg.conv_2d_nhwc_hwcf' op inferred input/output operand #1 has shape's dimension #2 to be 64, but found 16 ...

### What component(s) does this issue relate to?

Compiler

### Version information

Latest IREE ToT

**Comment by jpienaar** [comment]
Seems likely related to TFLite to TOSA converter but would need to verify depending on what pass fails. @NatashaKnk would you be able to take a look/narrow down where failure is from?

**Comment by NatashaKnk** [comment]
These two problems seem to be stemming from the same/similar issue - We are are inserting an unnecessary transpose in TosaToLinalg before those two operations. Looking into it.

**Comment by NatashaKnk** [comment]
Update:
The transpose isn't the issue after all, but the two errors are related.
In both cases this stems from the model trying to convolve mismatching shapes (the matmul error is a result of several passes that decompose Conv2D -> fully_connected -> matmul). 

Specifically, the (nhwc) Conv2D shapes are as follows:
input: 1x4x1x128xf32
kernel: 128x1x1x64xf32 
bias: 128xf32

and 

input: 1x3x1x64xf32
kernel: 512x3x1x16xf32
bias: 512xf32

In both of those cases, this is a mismatch in the input channel size between the input and the kernel. 
I've traced this all the way back to the flatbuffer importation, so this isn't a TOSA/lowering issue as far as I can tell, but it only gets picked up on the tosa level since there seem to be no matching verifiers for tfl.
Working on figuring out what could be causing the inputs shapes to be mismatched. My guess is something is going wrong with the inputs to the model itself (specifically, the kernel shapes are the ones that seem off), but I'm not sure yet.

**Comment by jpienaar** [comment]
Oh great find, thanks!

**Comment by jpienaar** [comment]
Oh wait: this could be TFlite flatbuffer being unable to differentiate between 1 and dynamic if I recall correctly. Which means we in some cases can't trust the shapes produced. If memory serves there was a change to enable differentiating but it would be in a newer flatbuffer.

**Comment by NatashaKnk** [comment]
Would this be the case even for non-1 shapes if they are coming straight from input?

**Comment by NatashaKnk** [comment]
Follow up - this seems to be a result of the fact that TFLite supports grouped convolution while Tosa doesn't. As a result the shapes are valid TFLite side (since the filter channel dim needs to be a factor of the input channel dim - which is the situation for both examples) but not tosa side. While working on the lowering, I'll send a fix that throws a clearer error message.

**Comment by NatashaKnk** [comment]
Just landed an internal change that decomposes grouped convolutions into a series of slices + standard convolution. Hopefully when it gets picked up the issue should be resolved.

**Comment by lundong** [comment]
Just following up: any update on this issue? Looks like the models are still failing.

**Comment by NatashaKnk** [comment]
Update (sorry this took so long): Both models should be fixed now, however we are having a bit of trouble bumping up the tf-nightly version used by IREE at the moment. So if it's of any help, you should be able to test them by updating the tf-nightly version locally.
(Working on resolving it in it's entirety)

**Comment by lundong** [comment]
Confirmed the issue has been fixed.
